### ISSUE TITLE
Trend/statistics reporting for clients and parcels

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#356]
### Describe the solution / feature you'd like

Every week, I create a report for the FoodBank managers on the number of parcels we had the following week, the family sizes and also the number of pets. See spreadsheet attached.

Note that these parcels are only ones that have successfully been packed and delivered. So parcels that have the status Called and No response, Parcel Denied etc are omitted from these stats.

If the app could have a new page called Reports where this table exists that would be great. Only viewable by Admins/Managers/Staff. Or a way to create the last weeks stats which I copy and paste into the google spreadsheet. Or worse case (which is what I currently do), a way to download the raw data from the database and I extract the data myself)

### Additional context

<img width="1208" alt="Screenshot 2024-05-22 at 16 48 08" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/00517e1b-7723-495f-a984-dcfad2017a69">

**Comment by Alex-Softwire** [comment]
Changelog: 

- Have added a reports table available to both admin & staff. 
- It currently counts parcels that have at some point been assigned the status "Parcel Completed", "Fulfilled With Trussel Trust" and "Delivered" - it shouldn't double count parcels, if the status' have been assigned twice. 
- It will group completed parcels by week, using the timestamp of the time that they were completed. 
- It should show everything from the first completed parcel to now.
- Deleted (but still delivered) parcels will be included
- Deleted clients are currently included in the total but not any of the family size or pet totals (as that information is no longer known) - By saving report data, this may be fixed in a subsequent ticket. 


Although a download to csv file button may be added later - for now one can do the following on the supabase console to download the raw data:
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/107864173/0fb61241-26c0-492c-b67c-eec49ff57c2e)

**Comment by Alex-Softwire** [comment]
QA: 

- Check everything in the change-log is valid 
This could include checking:
- Updating status' of parcels to see if they appear in the table. See whether the pet categories are calculated correctly.
- Testing whether the table is accessible to volunteers (it should not be).
- Testing the table layout on small browser sizes (though a future styling ticket may come later to fix this).
- Adding a completed parcel in the past (e.g 2022) to see if it will include data from it.

**Comment by kaydentsoftwire** [comment]
The table looks good and is not viewable as a volunteer 👍  but I think there may be a bug in the code somewhere here
For the w/c 2024-05-20, when I filter on the parcels table, I find 10 parcels that are either Delivered, Fulfilled with Trussel Trust or Collected, but in the table the row shows 0 all the way across
And for the w/c 2024-04-15, I find 17 in the parcels table with those filters but on the reports table I see the total as 164.
I tried to add a parcel as delivered for the last week but it did not change what was shown.
![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167894215/8c4136d9-96e3-4120-a7c9-4108078dd406)
It's possible I've misunderstood, so let me know if I'm missing something about how the table works?

Small things:
I would personally change the format of the date in 'week commencing' to match what we have in the parcels table, so for example we see 20/05/2024 instead of 2024-05-20.

Maybe we could raise a ticket about formatting the table so that:
- when viewed on a smaller screen it drops out the columns that are not Total and Pets Total?
- there is a dividing line or a gap between the section about humans/families and the section about pets?

**Comment by Alex-Softwire** [comment]
- The dates recorded on the table are the completion dates (event status dates for Delivered etc.) and not the packing dates. I think this seems the best date to use - given we're logging only completed parcels, but am not sure it's clear from the ticket lmk if you disagree.
- We include all parcels that have at one point had the status Delivered, not just ones whose last status is Delivered. So sorting by Delivered won't get the right number. It's like that so if you download the shopping list for a delivered parcel, it doesn't stop being delivered. 
Does this make sense/change things? Apologies for not making this as clear in the qa comments.

**Comment by Alex-Softwire** [comment]
Re the small things:

- Agree with the dividing line, was planning to add it but spoke to Kristina and left it out over time constraints. Will create a ticket for this? Also agree with the week commencing, would make things neater - thanks for spotting. 
- Not sure why all the columns are being dropped on smaller screens, will investigate.
Edit: Hmm I can't replicate this, could you take a screenshot?

**Comment by kaydentsoftwire** [comment]
Thanks for clarifying! That makes more sense. I think we can make a new ticket for the formatting, and QA passed! 

QA:
- [x] When I add a status of Parcel Collected, Delivered or Fulfilled with Trussell Trust, the total of that week increases by 1
- [x] I checked that the family size of a new collected parcel matched what is added on the table, and it does
- [x] When I add a second status of the above to the same parcel, the total does not increase
- [x] volunteer logins cannot view the table
- [x] First date shown is 1/1/24, which seems to correspond with the first completed parcel
- [x] It is possible to download the data as a CSV from supabase
- [x] If a delivery is added to a deleted client's parcel, the total increases by 1 but the others do not.

Sorry, I wasn't clear: dropping the columns apart from total on a very small screen was a suggestion, although perhaps not relevant.

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 months, assumed done
