### ISSUE TITLE
Parcel status filtering - change from "de-select to hide" to "select to filter"

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#395]
### Describe the solution / feature you'd like

When wanting to filter by Called & Confirmed, you have to deselect 21 other options. 

We should change this to:
- Open Last status filter
- all options are de-selected by default (showing no filtering)
 - tick a status to filter by that status.

Note from users: Should be able to filter all entries by a particular status without having to deselect all other last status options (eg currently to find all “shipping labels downloaded” you have to select last status and then untick all other boxes other than shipping labels downloaded)

**Comment by stonelink** [comment]
## Notes on parcel filtering
* The default state of the Last Status filter is to have all options selected other than _Deleted Parcel_ - so it's not the case that the default situation is "no filtering"
* The functional spec from the previous system shows the items in the filter droplists as unselected if there is no filtering applied (which is consistent with Dan's request)

## Planned spec 
* all filter controls behave as "no selection" => apply default filtering
* in all cases _except_ Last Status on the Parcels table, default filtering == no filtering
* for _Last Status_, default filtering == everything except _Deleted Parcel_
* ticking one or more of the checkboxes => filter to only show parcels that match the ticked state(s)
* (this replaces the default filtering rather than adding to it, so ticking _Deleted Parcel_ will work as expected)

Note that I had considered following the _(Select All)_ functionality used by Excel for filtering user rows, but that would require 3 clicks to show just one Parcel status (Select everything, Deselect everything, Select the thing you want),

**Comment by stonelink** [comment]
## QA Steps

On the Parcels page:
- reload the page (to have a default state) for the controls
- set the date filter to be approximately 2 months, so there is a reasonably large amount of data in the parcels table
- check that the page has an expected amount of content (e.g., > 100 rows)
- check that each of the three droplist filters above the table (Method, Slot and Last Status) have no checkboxes ticked (this is their default state), and that they each show a down arrow

In the Last Status droplist:
- tick one of the checkboxes for a status that you can see on a parcel in the table
- -> verify that the table is filtered to contain only parcels with that status, including the parcel that you were looking in the previous step
- tick another 1 or 2 of the checkboxes in the Last Status droplist
- -> verify that the table is filtered to contain only parcels whose last status is one of the three selected
- -> verify that the droplist filter button now shows a filter icon in place of the down arrow
- untick all the checkboxes in the list
- -> verify that the table returns to having parcels of all status except Parcel Deleted - scroll through the table to check that no parcels visibly have "Parcel Deleted" as their last status
- -> verify that the filter button now has a down arrow instead of the filter icon
- in the database, look in `parcels_plus` to find a parcel within the date range that's been entered on the page with the `last_status_event_name` value "Parcel Deleted" - and note the parcel's date and packing slot and client name
- back in the webapp, in the Last Status droplist tick "Parcel Deleted"
- -> verify that the table now shows the parcel that you noticed in the db
- untick the Parcel Deleted filter
- -> verify that the table returns to showing all parcels except "Parcel Deleted"

In each of Method and Packing Slot droplist filters:
- -> verify that no selection causes all parcels to show in the table (that match the date range and other filters)
- -> verify that selecting one or more options in the droplists filters the table to just show the selected states
- -> verify that having a combination of filter values shows Parcels that match all the set filters - e.g., 1 tick under Method and 2 ticks under Last Status shows only parcels whose method is the chosen one and whose last status is one of the two selected

**Comment by stonelink** [comment]
QA Passed on Safari and Chrome

**Comment by Stuart-Knowles-SW** [comment]
Has been in UAT for > 2 weeks, presumed done
