### ISSUE TITLE
Client DOB – need an option to keep blank

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#401]
### Describe the solution / feature you'd like

When entering a client DOB, need an option to leave it blank if we don't know

**Comment by stonelink** [comment]
That is, the Year for both Adults and Children should be optional (and the default)

**Comment by stonelink** [comment]
Blank year of birth 
= "Don't Know" or "Unknown" in UI, or no need to select from a droplist
= null in Database (in Families table)

Plan:
- update DB schema
- update form field (see precedent of optional child birth month)
- update client display in modal (perhaps "unknown age" for both adults & children)
- update client info on shopping list
- update batch client display & creation (see precedent of optional child birth month)
- ~update seed data to include some with unknown age~ (not changing seed data because of Snaplet shutdown)

~Note regarding Adults vs Children: because of the logic that defines a child as being < 16 years old, the Edit Client form still requires that the birth year be set for Children.~

**Comment by stonelink** [comment]
Hi @dan-langridge, there are a few options here and I'd like to get your opinion on how important the ideal fix is if it would delay the release.

There is an initial solution in review that makes the adult birth year nullable. Because of the logic that states that defines a child as being any person under 16, each child's birth year is still required. To make that optional might push the next release back by a day or two. 

The other question I have is whether _birth year_ is the appropriate UI for the callers to use. I wonder whether there was a misunderstanding of the requirements on our side early on... Before I took extended leave last year I discussed storing ages in the database using the year and potentially month - however that doesn't need to be the way it's presented in the UI. Changing the UI to have simple inputs for age in years and/or months (but still storing an inferred birth year & month) would probably push the release back by 3 days.

What are your thoughts on how this should work?

**Comment by dan-langridge** [comment]
I think being able to nullify for adult and child is a useful feature, not a problem if that pushes it back a few days.

I think the UI of adding a birth year (and month for child) is fine and gives us what we need. I don’t think it will be confusing. Plus entering the birth year gives us accurate info in the future, where as just entering how old they are at the time of entering the info will mean that info would go out of date right, and agree not worth adding the logic to work it out when we can just ask for birth year.

But yes, option to nullify both is going to be needed, thanks!

**Comment by stonelink** [comment]
## QA Notes
* Tested as Admin & Volunteer
* Tested on current Chrome and Safari 13.1 (via Browserstack)

QA steps:
* creation of client record with multiple adults and children, all with no information about birth year or month
* verify that client details (show "unknown age" for each person in client modal & shopping list
* edit client record to assign birth year to one of the adults and either birth year or birth year & month to one of the children
* verify that the list of adults and children is as expected

Note that an adult or child that has already been assigned a birth year/month cannot reset it to "unknown".

**Comment by dan-langridge** [comment]
Happy that this is complete.
