### ISSUE TITLE
Long Names on Shipping Labels overlap with CONTACT

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#405]
### Reproduction steps

When I create a shipping label for a client with a long name, it doesn't wrap and overlaps with the word CONTACT

### Expected behaviour

When I create a shipping label for a client with a long name it should wrap to the next line

### Screenshots / Videos

<img width="770" alt="Screenshot 2024-07-11 at 12 09 39" src="https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/80202270/6cc70f1e-a11c-414a-af02-f919efc3eb2d">

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by Stuart-Knowles-SW** [comment]
Progress tracked here https://softwiretech.atlassian.net/browse/VFB-307

**Comment by LeaHe188** [comment]
Hi Dan, this issue is currently being fixed, and I've noticed that sometimes the delivery instruction overflows because the label runs out of space (e.g the instruction has six lines). Just want to kindly check if this is a potential problem. If it is, we can fix this issue by adding more height to the label, if the label size is adjustable.

**Comment by dan-langridge** [comment]
Label width is fixed at 62mm however length is adjustable. We used to have 200mm length and want to try shortening it to 150mm to save labels. (It comes out on a continuous roll) I’d be more keen to implement a character limit on the delivery instructions text box to make it fit?On 21 Aug 2024, at 17:03, LeaHe188 ***@***.***> wrote:﻿
Hi Dan, this issue is currently being fixed, and I've noticed that sometimes the delivery instruction overflows because the label runs out of space. Just want to kindly check if this is a potential problem. If it is, we can fix this issue by adding more height to the label, if the label size is adjustable.

**Comment by Stuart-Knowles-SW** [comment]
Hi Dan, that's really useful info, thanks!

**Comment by LeaHe188** [comment]
Thank you! That's really helpful:)

**Comment by LeaHe188** [comment]
[ShippingLabels_2024_08_23_10_21_20.pdf](https://github.com/user-attachments/files/16726576/ShippingLabels_2024_08_23_10_21_20.pdf)
Hi Dan, we've made the changes based on your request, and also moved the name to the next line so that a longer name can be displayed on a single line before it's wrapped, does that look good to you?

In the file above you can find a very long name on the second page.

**Comment by LeaHe188** [comment]
I've noticed the request on https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/issues/455 as well, and plan to do these pdf tweaks in the upcoming ticket. Just want to kindly check if you'd prefer the version offered this morning, or do I follow the format on issue-455?

Thank you!

**Comment by dan-langridge** [comment]
Thank you! Changes you have made look good, thank you - if you can also add the 455 changes too that would great. Like putting Date Packed into 2 lines, and aligning AM | Delivery to centre to take it away from the postcode etc! On 23 Aug 2024, at 15:30, LeaHe188 ***@***.***> wrote:﻿
I've noticed the request on #455 as well, and plan to do these pdf tweaks in the upcoming ticket. Just want to kindly check if you'd prefer the version offered this morning, or do I follow the format on issue-455?
Thank you!

**Comment by LeaHe188** [comment]
Great, thanks Dan! Ticket 307 is merged now, and you can track those new changes in ticket 455, which is currently under progress.

**Comment by dan-langridge** [comment]
Happy that this is complete
