### ISSUE TITLE
Amend Dietary Form Responses

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#518]
### Describe the solution / feature you'd like

Amend the client dietary form responses the below:

**Dietary Requirements**

Don’t Know
Fresh Fruit
Fresh Veg
Garlic
Ginger
Chillies
Spices
Bread
Tea
Coffee
Pasta
Rice
Meat (No Pork)
Meat & Pork
Gluten Free
Dairy Free
Vegetarian
Vegan
Pescatarian
Halal
Diabetic
Nut Allergy
Seafood Allergy

**Other Items**

Hot Water Bottle
Blanket

**Comment by stonelink** [comment]
### Notes on "Don't Know"
- "Don't Know" should be represented by null entry in the db
- in the UI, if "Don't Know" is ticked then the remaining checkboxes should be disabled
- in the Shopping List, "Don't Know" should be written for null entry in db

### Notes on test data
- the existing data should ideally undergo migration, that specifically:
  - updates clients with Garlic/Ginger/Chillies/Spices under "Other Items" so that is under "Dietary Requirements"
  - the "No" options removed (i.e., No Bread, No Pasta etc.), with the inverse set in their absence (i.e., Bread, Pasta, ...)
  - most test clients should have "Fresh Fruit" and "Fresh Veg" ticked; perhaps the migration should be that all clients have these and then some specific test cases where:
    - the client has "Don't Know" for dietary
    - the client has some combination of no fruit/veg
  - "Hot Water Bottle" and "Blanket" are now singular
- the seed data will need to be updated - this will be covered by VFB-273

**Comment by stonelink** [comment]
### Next steps
* update the insert/update sprocs to handle null dietaryRequirements
* migration for existing data

**Comment by stonelink** [comment]
## QA Notes
* Tested as Admin & Volunteer
* Tested on current Chrome and Safari 13.1 (via Browserstack)

QA steps:
* Check a random selection of existing client records, and verify that the "Dietary Requirements" and "Other Requirements" in both the Client Details dialog and Shopping List are consistent with the list on this ticket - that is:
  * no old entries such as "No Beef" or the plural of "Blankets"
  * the order of the entries is consistent with the above
* create a new client record and leave "Don't Know" ticked under Dietary Requirements
  * verify that this shows as expected in the Client Details dialog and Shopping List
* create a new client record with a selection of Dietary and Other Requirements
  * verify that this shows as expected in the Client Details dialog and Shopping List
* edit an existing client to select & deselect different items, and verify behaviour
* edit a client record that has "Don't Know", give it a selection and verify behaviour

**Comment by dan-langridge** [comment]
Happy that this is complete.
