### ISSUE TITLE
Some Shopping Lists spill onto 3 pages - need to be 2 pages

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#525]
### Reproduction steps

When I print a Shopping list, it sometimes spills onto 3 pdf pages. In this scenario it is because the voucher number goes onto 2 lines, however if we add more items to the list this would still be an issue.

### Expected behaviour

When I print a Shopping list, it should be 2 pages.

Steps to resolve this:
1. Reduce column width for 'Done' - this only needs to be very narrow for a user to tick the item. This would allow the Item Description, Quantity and Notes column to have more width and the text would wrap less.
2. Remove size of gap between  'List Type' and 'Name' table.
3. Make top section into a table with 2 columns (Voucher Number, Packing date, slot, collection date, site, list type...)

### Screenshots / Videos

[ShoppingList_2024_10_17_12_14_28.pdf](https://github.com/user-attachments/files/17411383/ShoppingList_2024_10_17_12_14_28.pdf)
[ShoppingList_2024_10_17_12_13_28.pdf](https://github.com/user-attachments/files/17411384/ShoppingList_2024_10_17_12_13_28.pdf)

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment]
Hi @dan-langridge 

How do the lists in this file look? 

[devShoppingList_2024_10_23_22_58_35.pdf](https://github.com/user-attachments/files/17498645/devShoppingList_2024_10_23_22_58_35.pdf)

I've made most of the changes you suggest, and tightened and tidied some things. I haven't made the top section two columns because it looked cramped, so thought I'd check your thoughts on whether that is necessary. 

Also I'm wondering: in the household summary, I think 'Gender Breakdown' isn't redundant because it is in the Adults & Children info underneath. If it's important to know the gender of the client, that's the first adult. Can 'Gender Breakdown' be removed?

Thanks,
Lincoln

**Comment by dan-langridge** [comment]
Yeah that works well, thanks Lincoln!

**Comment by stonelink** [comment]
## QA Notes
* Tested as Admin
* Tested on current Chrome and Safari 13.1 (via Browserstack)

A large number of shopping lists have been generated recently for families of different sizes, as part of testing this and other tickets, and each have been approximately 1.5-1.75 pages long. This includes generating multiple shopping lists in one PDF.

**Comment by dan-langridge** [comment]
Happy that this is complete.
